spring:
  cloud:
    gateway:
      routes:
        - id: admin-service-route
          uri: lb://admin-service
          predicates:
          - Path=/admin-service/**
        - id: ai-service-route
          uri: lb://ai-service
          predicates:
          - Path=/ai-service/**
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
          - Path=/auth-service/**
        - id: doctor-service-route
          uri: lb://doctor-service
          predicates:
          - Path=/doctor-service/**
        - id: patient-service-route
          uri: lb://patient-service
          predicates:
          - Path=/patient-service/**
        - id: payment-service-route
          uri: lb://payment-service
          predicates:
          - Path=/payment-service/**
        - id: service-api-route
          uri: lb://service-api
          predicates:
          - Path=/service-api/**