spring.application.name=backEnd

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_brain_med
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# SQL init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# File upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Server
server.port=8080
